### PR TITLE
Clearance for Version 5.1.1

### LINKED ISSUE #278: Hotfix 5.1.1 checklist
### Summary
This is a discussion page of the issues that have been fixed and are to be fixed in version 5.1.1.
Please feel free to drop messages about the issues to be fixed but not mentioned in your opinion.

#### pspm_dcm
Missing epochs were not processed properly due to messy channel and data array referring #266 
Empty epochs not sorted in _pspm_dcm_ #280 
#### pspm_scr_pp
GUI unexpectedly throw warnings #255 
#### pspm_split_sessions
GUI issue that leads to software crash #262 
GUI accepts too many data files and missing epochs #269 
Missing epochs were not processed successfully #272 
#### miscellaneous
Welcome texts have not been updated #260 
Display issue for some GUI windows #259 #264 #265

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #278 .

Changes proposed in this pull request:
- Update documents

### CODE REVIEW

**Comment by teddychao** [comment]
@dominikbach 
The release notes seems a little weird. It includes the release notes from the initial version, but its title shows like *PsPM Version X.X Release Notes*. Would you mind me to change it to *Release Notes for PsPM*, and change the order of release notes from newer to older? I guess it would be easier for users. Thanks.

**Comment by SerenXia** [comment]
This is how the main GUI looks like:
image

The texts are a bit too small, but for me acceptable.

**Comment by teddychao** [comment]
> This is how the main GUI looks like:
> image
> 
> The texts are a bit too small, but for me acceptable.

Hi Yanfang,

Thanks for the feedback.

Can I know the screen resolution of your computer?
Mine looks like this
image
Thanks.

Best wishes
Teddy

**Comment by SerenXia** [comment]
> > This is how the main GUI looks like:
> > image
> > The texts are a bit too small, but for me acceptable.
> 
> Hi Yanfang,
> 
> Thanks for the feedback.
> 
> Can I know the screen resolution of your computer?
> Mine looks like this
> image
> Thanks.
> 
> Best wishes
> Teddy

sure. I have 1920x1080

**Comment by teddychao** [comment]
> sure. I have 1920x1080

Thank you Yanfang. I need to adjust the window size to make it look ok with different screen resolution. Thank you for your help.

**Comment by teddychao** [comment]
UI for windows is ok now. I noticed the attribution text at the bottom is very small and hard to read. Now it is larger and clearer.
image

**Comment by SerenXia** [comment]
current version works perfectly on my computer (win10) :)

**Comment by dominikbach** [comment]
Screenshot of the current version on MBP without external screen:
image

Batch GUI feedback:
1. Pupil convert and gaze convert appear twice in the menu (once under "Data preprocessing" and once under submenu "Pupil & eye tracking"
2. Order of data types under "Data preprocessing" should match "First level models"

Release notes missing in manual

**Comment by teddychao** [comment]
image
image
Main GUI in Mac is now stable and not affected by the screen resolution now

**Comment by teddychao** [comment]
image
image

I finally get this done... the Linux version looks fabulous.

**Comment by teddychao** [comment]
@dominikbach Would u suggest to add #282 to the hot fix 5.1.1? #282 has been merged into the develop branch. If not, I need to use a specified branch instead of the develop branch to release the hotfix release, thanks.
By the way, #288 is not a general issue, so even if it is included in 5.1.1, it seems not necessary to mention it in the release notes either...

**Comment by dominikbach** [comment]
My suggestion:
- include #282 and mention it in release notes, but no further explanation in the manual. This is not meant for basic users at this stage. 
- include #288 but don't mention it in the release notes.

Could you also update the order of data types in the preprocessing menu to be in line with first level GLMs? It is a minor change but looks nicer.

**Comment by teddychao** [comment]
Sorry @dominikbach I was trying to sort the GLM in first level but I forgot yesterday... It has been sorted now. I also fixed the names in the dropdown list to make them consistent between main GUI and batch editor
image

**Comment by teddychao** [comment]
@dominikbach I have updated the dropdown list in the GUI and make it consistent with batch editor. I also updated the manual, develop guide and release notes in this pull request. Could you please approve this pull request so I can make the release 5.1.1. Thanks!

**Comment by dominikbach** [comment]
@teddychao 
My point was that the Matlabbatch GUI menu "Data preprocessing" has a different ordering from the Matlabbatch GUI menu "First level. 

The order should be the same, starting with SCR (i.e. following the current ordering in the first-level menu).

Could you kindly fix that before merging.

Thanks.

**Review by dominikbach — APPROVED** [review]

**Comment by teddychao** [comment]
> @teddychao
> My point was that the Matlabbatch GUI menu "Data preprocessing" has a different ordering from the Matlabbatch GUI menu "First level.

Sorry @dominikbach  I am a little confused, could you please check this comparison pdf and let me know where you are not happy with? I assume the difference is the batch editor menu has two levels while the main GUI has only one level, for data preprocessing for example. Would you prefer me to generalise them to only one level? 
[compare_menu_batch_main.pdf](https://github.com/bachlab/PsPM/files/6874958/compare_menu_batch_main.pdf)

**Pull request merged**
