### PR TITLE
Improving UI

### PR DESCRIPTION
**Pull request by teddychao**
Changes proposed in this pull request:
- Adding a help button on the main screen, linking to the help text document.
- Adding a feedback button on the main screen, linking to the GitHub forum.
- Improving UI design to make it more clear.

### CODE REVIEW

**Review by dominikbach — CHANGES_REQUESTED** [review]
Great idea to refresh the design! A few points:
1. the "help" link opens the lyx file in text mode - this is not ideal. Is there a way of opening the pdf copy of the version that is being used (and of the latest downloadable version for expert users in the development version)? Or just the user's local pdf? Both options would require updating the PDF and putting it into the doc folder each time a new version is released.
2. Instead of "feedback" I'd suggest somethign like "Open issue"
3. The traditional red color (which only I seem to like) is gone - deliberate choice? In any case, it's a brand issue so we should discuss it in the team.
4. Could you check the fonts on different operating systems?

**Comment by teddychao** [comment]
Many thanks for the feedback @dominikbach 
> 1. the "help" link opens the lyx file in text mode - this is not ideal. Is there a way of opening the pdf copy of the version that is being used (and of the latest downloadable version for expert users in the development version)? Or just the user's local pdf? Both options would require updating the PDF and putting it into the doc folder each time a new version is released.
Yes I agree very much linking the help button to a PDF is better. It is currently to the .lyx document because that there is no PDF copy available in the current official release or the local folder. I would export a PDF version of the manual and add it to the next official release. The help button will be linking to the local pdf document in the next official release, although currently with a temporal link to the official [website](http://pspm.sourceforge.net) of PsPM.
> 2. Instead of "feedback" I'd suggest somethign like "Open issue"
Corrected.
> 3. The traditional red color (which only I seem to like) is gone - deliberate choice? In any case, it's a brand issue so we should discuss it in the team.
No problem, I have updated the background colour back to red.
> 4. Could you check the fonts on different operating systems?
Yes! The [Microsoft Windows](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list), [Apple MacOS](https://support.apple.com/en-gb/HT211240) and [Linux](http://rigaux.org/font-family-compatibility-between-linux-.html) have both Tahoma and Verdana available.

I have updated the UI by using the new App Designer in MATLAB. It should be compatibile for MATLAB versions between 2018 and 2021.
image
Please feel free to let me know what you think of it 😀

**Comment by dominikbach** [comment]
> > 1. the "help" link opens the lyx file in text mode - this is not ideal. Is there a way of opening the pdf copy of the version that is being used (and of the latest downloadable version for expert users in the development version)? Or just the user's local pdf? Both options would require updating the PDF and putting it into the doc folder each time a new version is released.
> 
> Yes I agree very much linking the help button to a PDF is better. It is currently to the .lyx document because that there is no PDF copy available in the current official release or the local folder. I would export a PDF version of the manual and add it to the next official release. The help button will be linking to the local pdf document in the next official release, although currently with a temporal link to the official [website](http://pspm.sourceforge.net) of PsPM.

Sounds good, for the development version the link can also be empty (and the official website is not on sourceforge!)

> 
> I have updated the UI by using the new App Designer in MATLAB. It should be compatibile for MATLAB versions between 2018 and 2021.
> image
> Please feel free to let me know what you think of it 😀

I'll survey the researchers who work with it!

**Review by dominikbach — CHANGES_REQUESTED** [review]
This looks great. 

At the bottom of the GUI, some words are missing.

Also, I'd suggest changing this into

"The PsPM Team, University College London"

without the copyright and without my name.

**Comment by teddychao** [comment]
I have included the manual in PDF format in this commit. If the PDF file is uploaded and merged into the develop branch, users shall be able to see the PDF file directly by clicking the _help_ button.

**Review by dominikbach — CHANGES_REQUESTED** [review]
this looks great now! 

However, the help button did not work (yet? Does it have to be merged first?), and the feedback button not either. 

When clicking on the feedback button more than once in a row, then I see the following error message:

Error using matlab.ui.Figure/set
Invalid or deleted object.

Error in matlab.hg.internal.openfigLegacy (line 117)
                set(fig,'Visible',savedvisible);

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);

Error in gui_mainfcn (line 233)
            gui_hFigure = local_openfig(gui_State.gui_Name,
            'reuse',gui_Visible);

Error in pspm (line 55)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)pspm('PsPM_ButtonDownFcnForum',hObject,eventdata,guidata(hObject)) 
Error while evaluating DestroyedObject Callback.

**Comment by teddychao** [comment]
> However, the help button did not work (yet? Does it have to be merged first?), and the feedback button not either.

Apologies, that is because the old GUI has not been updated after I modified the two functions for the new GUI. I have updated those two buttons and they are currently working ok like the new GUI.
Yes the help button would not work before we upload the help text to the develop branch. I have included the PDF in this commit, so it shall be working after being merged into the develop branch.
The .html file is the report for showing the results of converting the old GUIDE-based GUI into the new GUI. I have updated the gitignore file to ignore this file as it should not be included in the official release for users.

**Pull request merged**
