### PR TITLE
Issue 157 (completed)

### PR DESCRIPTION
**Pull request by teddychao**
Changes proposed in this pull request:
- Drafted a function to detect the clipping.

Requires appropriate data and parameters for testing.

### CODE REVIEW

**Comment by dominikbach** [comment]
Here are two examples from a Coulborn recording 
[Uploading Two_SCR_clipping_examples.zip…]()
system.

**Comment by teddychao** [comment]
Clipping can be detected in this version of code, but parameters have to be specified. Results of the two_SCR_clipping_examples with the optimal parameters are shown as below.
Screenshot 2020-12-16 at 11 44 18
Screenshot 2020-12-16 at 11 44 38

**Comment by dominikbach** [comment]
Hi Teddy, after approving issue #158 fix there is a conflict, could you update the branch? As discussed, we can then merge after implementing the optimal parameters. Thanks! Dom

**Comment by teddychao** [comment]
> Hi Teddy, after approving issue #158 fix there is a conflict, could you update the branch? As discussed, we can then merge after implementing the optimal parameters. Thanks! Dom

Sure Dom, I will find the conflict and update the branch then. Thanks! Teddy

**Comment by teddychao** [comment]
Looks like the issue is caused by activation. Try to contact the license centre at Zurich after the holidays..
Screenshot 2021-01-02 at 00 28 07

**Comment by teddychao** [comment]
Screenshot 2021-01-18 at 16 45 23
The updated version of the code is able to provide more accurate clipping detection and requires less computing.
The recommend parameters are able to detect clipping well in the tested dataset here: https://zenodo.org/record/1887738#.YAW8fS2l1UN.

**Review by dominikbach — APPROVED** [review]

**Pull request merged**
