### PR TITLE
Fix issue 698 -- new GUI

### LINKED ISSUE #698: New GUI for PsPM 7.0
### Feature Description

This is a draft for the new PsPM GUI. Feedback welcome. More background in #603 .
PsPM GUI 20240419

We may get rid of the GUIDE-based GUI entirely and only use the mlapp.

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #698.

Changes proposed in this pull request:
- Add new GUI for PsPM 7.0.
- The Matlab-guide-based UI has been disabled from PsPM entrance.
  - A message will be promoted if the user is using an older version of MATLAB that cannot support App Designer.

### CODE REVIEW

**Comment by teddychao** [comment]
New UI
image

Promoted message
image

**Comment by dominikbach** [comment]
1. White descriptors need to be changed to the original proposal, see https://private-user-images.githubusercontent.com/3895146/332115923-ea84b6bd-c60c-4b77-be67-8fd7a13ac942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjMwOTMsIm5iZiI6MTcxNzQyMjc5MywicGF0aCI6Ii8zODk1MTQ2LzMzMjExNTkyMy1lYTg0YjZiZC1jNjBjLTRiNzctYmU2Ny04ZmQ3YTEzYWM5NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMTM1MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWRjOGE5Yjc3ZTVmYjE1YjhiYzFhNzM4Yjg0ZjUxMTM4NTdlNTRjNWQ3NmI5M2IxYmI5Njc3ODBiY2VjYmQzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r2jmr4svgQJpUXqReuOI79yb3uGc8Adw2TTG0adVHHU
2. Can we have the white outline around boxes as in the above proposal?

**Review by dominikbach — CHANGES_REQUESTED** [review]
see comments.

**Comment by teddychao** [comment]
Hi @dominikbach 

Thank you so much for pointing out the errors in this draft. The issues 1 and 3 have been fixed in the current version.
For issue 2, I tried to add the lines, and I feel it is a little ugly, because the corners are not rounded and in line with the buttons. Could you please have a look at this version and let me know how you think?
Many thanks

image

**Review by dominikbach — APPROVED** [review]

**Comment by teddychao** [comment]
This is how it looks like now
image

**Pull request merged**
