### PR TITLE
Update GUI font family and size

### LINKED ISSUE #258: Typeface generalisation
### Feature Description
The main GUI is currently built with Verdana, while other GUIs are still using various typefaces (Helvetica/Arial, Courier/Courier New). May need to make them consistent throughout the software.

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #258, #259 and #265 .

Changes proposed in this pull request:
- Improve the UI for the current features
  - data display
  - data editor
- Data display now has a module for showing the metadata of the imported file.

### CODE REVIEW

**Review by dominikbach — COMMENTED** [review]
Display does not work on my mac book pro with Matlab 2019b.

Screenshot after loading a data file:
image

**Review by SerenXia — COMMENTED** [review]
not really working...

1. same fonts issue in the main page (red GUI): 
   1a. initial window showed only parts of texts
GUI_main

   1b. texts were shown properly after zooming in manually
Gui_main_zoomin

2. same issue as Dominik had: the display data function did not work after loading a datafile
display

3. same fonts issue in review model window as the main GUI:
 3a. parts of the texts were hidden in the initial window
model_review
 
 3b. seems alright after zooming in manually
model_review_zoomin


4. the other batches and functions look good

**Comment by teddychao** [comment]
The incomplete text display is caused by the text block size. Some text blocks are too narrow so the text cannot be displayed completed. I am adjusting the text blocks to make them consistent with others (e.g. the buttons). I am going to add adjusted initial window size so that text can be displayed completely.

**Comment by teddychao** [comment]
@SerenXia Could you please kindly try the new screen in this branch please? I have set up the new main GUI window size for Windows PC based MATLAB. Please feel free to let me know if it works for you, thanks.

**Comment by teddychao** [comment]
@dominikbach hi dom, I have added a module for displaying the summary of the file. However, I noticed you mentioned in the issue that the channel should be shown there. However, I found users can select something in the options below the plot, which indicates that the channel information could be dynamic. May I confirm with you this dynamic channel information (maybe including other dynamic parameters when applicable) the feature requested? Thanks!

**Comment by dominikbach** [comment]
GUI: font size for "second level" and "more" is smaller than for "data preparation", "data preprocessing", etc.

**Comment by dominikbach** [comment]
Display: The summary should list all channels with number and type. The interactive fields for plotting show all channels but not in order and without their numbers. Users will want to have a simple overview of the channel numbers for functions that take channel numbers as input argument.

Further points: currently the x-label of  wave channel plot is half covered by the "display options" underneath.

**Comment by SerenXia** [comment]
the current version does not work well in windows.

1. GUI main interface: still having texts hidden
pspm_gui_main_origin

2. main interface looks good after zooming in
3. model review interface looks good now... no need to zoom in to check texts

4. display interface looks terrible, but the function works.
pspm_gui_display_origin

**Comment by teddychao** [comment]
@SerenXia 

Thank you for kindly testing the software.

The reason why `pspm_display` looks "horrible" is the scale of text size between Mac and Windows are different. As the solution, I have updated the GUI to use the normalised text size scale, which is theoretically able to unify the look of GUI between Mac and Windows (presumably also linux but I have no device to test). The current version should be ok for it.

However, this is not the final solution, because the current GUIDE will be removed in a future release of MATLAB, although some users may prefer to use legacy versions of software. However, for those who updated the software to the latest version, the new AppDesigner would be necessary for them. I have also updated the AppDesigner version of `pspm_display` in this version, as `pspm_display_App.mlapp`. Please note, this is the basic converted version and has not been tested for its functioning. I am still working on it. If you could kindly let me know if the current version of `pspm_display.fig` looks less terrible for you, it would be grateful.

Many thanks
Teddy

**Comment by teddychao** [comment]
@dominikbach 

Thank you for the suggestions of the main GUI. I did not notice the text size of the subtitles for those buttons. I have also updated the text size of the main GUI to unify the look between Windows and Mac. I enlarged the pop down menu as the old one seems too small and the rectangle looks weird. The current version should be better. I am still working on the other suggestions at the moment.. 

Many thanks
Teddy

**Comment by dominikbach** [comment]
just checked the latest version, on MacBookPro.
- main GUI: too small, square, needs to be increased to > 4 x original size to see all texts
- main GUI: headers "more" and "second level" are closer to the buttons underneath than the headers "data preparation" etc. in the same line (meaning that they become visible later than the others when increasing the window size)
- display: file summary not yet implemented?

**Comment by dominikbach** [comment]
pspm_app_beta does not run on Matlab 2019b:

Undefined function 'getRunningApp' for input arguments of type 'pspm_App'.

Error in pspm_App (line 686)
            runningApp = getRunningApp(app);

Error in pspm_app_beta (line 14)
pspm_App;

**Comment by teddychao** [comment]
> pspm_app_beta does not run on Matlab 2019b:
> 
> Undefined function 'getRunningApp' for input arguments of type 'pspm_App'.
> 
> Error in pspm_App (line 686)
> runningApp = getRunningApp(app);
> 
> Error in pspm_app_beta (line 14)
> pspm_App;

Many thanks Dom for the feedback. I am currently using 2021a on macOS Big Sur, so I guess the issue is caused by the different version of MATLAB. I am installing a virtual machine of windows with matlab 2019 (maybe most people are using) to test it. Presumably this is a function available in a newer version of MATLAB, although MathWorks told me [AppDesigner was available for users with MATLAB 2016 or newer](https://uk.mathworks.com/matlabcentral/fileexchange/66087-guide-to-app-designer-migration-tool-for-matlab).

**Comment by teddychao** [comment]
> * display: file summary not yet implemented?

The screenshot above is presumably showing what we see by double-clicking pspm_display, instead of running it in batch. This is how it looks like by running it in batch. Admittedly, the _file_summary_ module is still ugly and needs further work.
image

**Comment by SerenXia** [comment]
Hi Teddy,

Unfortunately none of the above works in my matlab 2018b (win10).

the app just did not work, no matter how I started it.
Screenshot 2021-07-07 121941

the fonts in pspm_display.fig still look too large to be read in windows.
pspm_display_fig

**Comment by SerenXia** [comment]
and fonts in the main GUI looks not good in windows as well...
image

**Comment by teddychao** [comment]
> and fonts in the main GUI looks not good in windows as well...
> image

Hi,

Thanks for helping test the GUI.

I have installed a windows virtual machine on my computer, could you please wait for a few seconds to allow me to test it by myself? Many thanks

Best regards,
Teddy

**Comment by teddychao** [comment]
image

Hi,
the main GUI for windows has been ok now. It should be consistent across windows 7, windows 8, windows 10 and windows 11.
Thanks.

**Comment by teddychao** [comment]
And the Mac version, showing all the content with an appropriate size..
image

**Comment by teddychao** [comment]
@dominikbach 
The reason why the new AppDesigner style main GUI cannot run is the poor compatibility of early version MATLAB for AppDesigner. I have tested it by rewriting some code in pspm_app.mlapp and now it works, although there could be potentially still some bugs. It looks like the AppDesigner style main GUI needs to be rewritten to improve the compatibility, but I am sure it is supported by MATLAB 2016a or a newer version. I am happy to discuss with you about this later. Many thanks.

**Comment by teddychao** [comment]
> Hi Teddy,
> 
> Unfortunately none of the above works in my matlab 2018b (win10).
> 
> the app just did not work, no matter how I started it.
> Screenshot 2021-07-07 121941
> 
> the fonts in pspm_display.fig still look too large to be read in windows.
> pspm_display_fig

Thanks a lot for the screenshot @SerenXia . I am working on *pspm_display* at the moment. I have understood your issue and I will let you know when I finish if you do not mind. I will use the virtual machine to test the display, so hopefully next version will be less terrible :).

**Comment by teddychao** [comment]
*pspm_display* is now beautifully displayed for Windows..  and the UI is compatibly designed for Mac too.

I need to update the plot function for the independent use of *pspm_display*

image
image

**Comment by SerenXia** [comment]
The fonts look good now.

But the main GUI window looks a bit too wide on my computer... probably due to resolution? I have 1920*1080.
gui main

fonts in pspm_display window looks good to me as well, only that there is no summary information.. 
display

**Comment by dominikbach** [comment]
Specs for the file summary:
- activated by *loading* a file via the menu/via command line, rather than by plotting
- "Data source" -> "File name"
- "Duration" -> "Recording duration
- remove "position of marker"
- instead, list all channels with number and type (as per settings.chantypes(...).description)

**Comment by teddychao** [comment]
The UI needs to be generalised across all the windows. I wrote a new function *pspm_ui* to control these parameters.

**Comment by dominikbach** [comment]
Feedback on the latest changes (on MacBookPro):
- main GUI looks fine
- pspm_display: could be wider by default, header "Recording duration" is broken into two lines with the second one invisible.
- File summary: 
- - add "s" after recording duration or change header into "Recording duration (s)"
- -channel numbers should be 1 - 2 - 3, ... and not 1,1 - 2,1 - 3,1 - ...
- - as per my last comment, channel type for channel k should be displayed as settings.chantypes(strcmpi({settings.chantypes.type}, data{k}.header.chantype)).description, not as data{k}.header.chantype

**Review by dominikbach — APPROVED** [review]

**Comment by teddychao** [comment]
image
@dominikbach Texts in `Channels` are now aligning to the left.

**Pull request merged**
