### PR TITLE
Set up GitHub Actions support for testing PsPM

### LINKED ISSUE #303: Move testing platform from Jenkins to GitHub Actions
### Feature Description
Jenkins is going to retire at the end of this year. GitHub Actions will become the platform for code testing. This issue records the transition from Jenkins to GitHub Actions.

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #303  .

### CODE REVIEW

**Comment by teddychao** [comment]
Because Jenkins will always be called if I test GitHub Actions here, I forked PsPM under my own repository and test GitHub Actions there. Jenkins won't be called there so we can save some resources :)

**Comment by teddychao** [comment]
@dominikbach Sorry for disturbing again Dom. May I know your suggestions about the ImportTestData folder? It seems that some test data is saved on Jenkins server but not uploaded to GitHub develop branch. Such data is essential for testing PsPM. Currently there are two solutions. First, save the ImportTestData folder on GitHub develop branch so GitHub Actions can use such data. Second, save the ImportTestData folder on GitHub Actions server. I guess it would be better to select the second option, but it may be better to confirm with you first, thanks!

**Comment by dominikbach** [comment]
@teddychao I assume that including the test data in the develop branch would make it much bigger? Some data files can be quite large. I would also prefer the second option.

**Comment by teddychao** [comment]
@dominikbach Thanks for your comment, I have got a solution which should be working ok within the GitHub Actions free plan.
image

**Comment by teddychao** [comment]
Just a quick update. I have confirmed with GitHub Actions that it supports OneDrive file downloading through REST API. It looks quite interesting and I am now trying to implement it in our project. Thanks.

**Comment by teddychao** [comment]
Updates today:
I have contacted both GitHub Actions and Microsoft about the issue. Here are the latest information:
* Microsoft/OneDrive has not set up a formal or suggested pipeline for implementing data sharing between OneDrive and GitHub Actions.
* Microsoft/OneDrive has provided the useful OneDrive REST API that may help to download files to GitHub Actions, but it is a little complicated and I need to learn to use it.
* Microsoft did not confirm whether it is technically possible to download files to GitHub Actions, whilst GitHub Actions said it was possible.

This is the transcript: https://liveuclac-my.sharepoint.com/:w:/g/personal/skgtdz0_ucl_ac_uk/EdiXLARtd3pEtQsSOMTXc_8BvhEcYnf8kDdlsGHclZN77w?e=F0xY65

**Comment by teddychao** [comment]
This is a legacy pull request. We have implemented GitHub Actions in other pull requests.

**Pull request closed without merging**
