### PR TITLE
Fix Issue 201

### LINKED ISSUE #201: Implement new split_sessions options.missing in GUI

### PR DESCRIPTION
**Pull request by teddychao**
Fixes #201 .

Changes proposed in this pull request:
- Implement new split_sessions options.missing in GUI

### CODE REVIEW

**Comment by teddychao** [comment]
Update 30th March: being discussed with Jelena at the moment.

**Comment by dominikbach** [comment]
I think the missing epochs file should be an optional feature. I guess that on most cases, users won't provide a missing epochs file.

**Comment by dominikbach** [comment]
The way this is implemented now, the batch job cannot be run if no missing options file is specified.

**Review by dominikbach — CHANGES_REQUESTED** [review]
see comment

**Comment by teddychao** [comment]
> The way this is implemented now, the batch job cannot be run if no missing options file is specified.

Many thanks for reminding me of that. It has been fixed now 😀 
The description and level of options were also updated.

**Review by dominikbach — APPROVED** [review]
Perfect, I made some minor changes to help text and tags; ready to be merged after checks have passed.

**Pull request merged**
