### PR TITLE
Fix issue 559

### LINKED ISSUE #559: pspm_convert_ppg2hb supports both options.replace and options.channel_action
This should have been removed with the switch to pspm_options.

### PR DESCRIPTION
**Pull request by teddychao**
### Summary
This pull request aims at
1. Solving the issue #559.
2. Review all the `cfg_run` functions for preparing the next release.
3. Make sure all the `cfg_run` functions initialise `options` before using it and check fields are available in `job` before transferring data to `options`.

### New functions
There is now a new function `pspm_update_struct`. The function can assess the `struct` fields and transfer the information to the new struct when the field is available.

### New test function
There is now a new text function `pspm_update_struct_test`. The function tests whether `pspm_update_struct` can transfer field values correctly.

### Function-specific updates
| Function | Updates |
|:--|:--|
| `pspm_cfg_run_artefact_rm` | Use `pspm_update_struct` (lines 4, 19--24) |
| `pspm_cfg_run_contrast1` | Use `pspm_update_struct` (lines 18) |
| `pspm_cfg_run_contrast2` | Use `pspm_update_struct` (lines 37) |
| `pspm_cfg_run_data_convert ` | Use `pspm_update_struct` (lines 18--19) |
| `pspm_cfg_run_dcm` | Initialise `options` (line 12). Use `pspm_update_struct` (lines 82, 90--102) |
| `pspm_cfg_run_downsample` | Initialise `options` (line 3). Use `pspm_update_struct` (line 9) |
| `pspm_cfg_run_ecg_editor` | Use `pspm_update_struct` (line 20--22) |
| `pspm_cfg_run_export` | Use `pspm_update_struct` (line 15) |
| `pspm_cfg_run_extract_segments` | Use `pspm_update_struct` (line 45) |
| `pspm_cfg_run_find_sounds` | Initialise `options` (line 5). Use `pspm_update_struct` (line 18, 24) |
| `pspm_cfg_run_find_valid_fixations` | Use `pspm_update_struct` (line 23, 33, 46) |
| `pspm_cfg_run_gaze_convert` | Initialise `options` (line 4). Use `pspm_update_struct` (line 5, 8) |
| `pspm_cfg_run_get_markerinfo` | Use `pspm_update_struct` (line 9) |
| `pspm_cfg_run_glm` | Initialise `options` (line 5). Use `pspm_update_struct` (line 72, 107) |
| `pspm_cfg_run_glm_sps` | The `[]` at line 22 and 25 (were 35 and 38) for `soa` was removed because it does not seem to be necessary. |
| `pspm_cfg_run_import` | Initialise `options` (line 86). Use `pspm_update_struct` (line 51--53, 78--83, 87) |
| `pspm_cfg_run_interpolate` | Use `pspm_update_struct` (line 6, 18) |
| `pspm_cfg_run_merge` | Initialise `options` (line 8). Use `pspm_update_struct` (line 10--13) |
| `pspm_cfg_run_pp_emg_data` | Use `pspm_update_struct` (line 4) |
| `pspm_cfg_run_pp_heart_data` | Use `pspm_update_struct` (line 37, 40, 46, 53, 59--66, 72, 80) |
| `pspm_cfg_run_proc_illuminance` | Use `pspm_update_struct` (line 11--12) |
| `pspm_cfg_run_pupil_correct` | Use `pspm_update_struct` (line 10--19, 21--25) |
| `pspm_cfg_run_pupil_preprocess` | Use `pspm_update_struct` (line 14, 20) |
| `pspm_cfg_run_pupil_size_convert` | Use `pspm_update_struct` (line 6) |
| `pspm_cfg_run_segment_mean` | Use `pspm_update_struct` (line 6) |
| `pspm_cfg_run_sf` | Use `pspm_update_struct` (line 65--68) |
| `pspm_cfg_run_trim` | Use `pspm_update_struct` (line 4) |

### CODE REVIEW

**Comment by teddychao** [comment]
Hi @dominikbach 
I am using this pull request to review and polish the cfg_run functions. I think some of them are outdated and should be fixed in line with the new `pspm_options`. I will mark it to be "ready for review" when I finish.
Best wishes
Teddy

**Comment by dominikbach** [comment]
In principle this looks good to me but I haven't checked all the details in all functions. Since there are no automated tests for the GUI, has any plausibility test been performed in the GUI?

**Comment by teddychao** [comment]
> In principle this looks good to me but I haven't checked all the details in all functions. Since there are no automated tests for the GUI, has any plausibility test been performed in the GUI?

The GUI is not included in the test functions, so I tested them by myself. I can double check by replicating the test functions in the GUI to see if they work ok. I will send the updates to this pull request. Thanks for letting me know your thoughts

**Comment by teddychao** [comment]
Hi @dominikbach 
Many thanks for approving this pull request.
I have requested @MadniAbdulWahab  to kindly test this branch by using the beta branch of pre-release 6.1.1 that has merged this branch. When he is happy with the updates, I will be able to merge this branch into the develop branch. I can also do some manual checking before getting Abdul's feedbacks.
Best wishes
Teddy

**Review by dominikbach — CHANGES_REQUESTED** [review]
see related pull request #577

**Comment by dominikbach** [comment]
The first step (import) of the GLM tutorial yields the following error:
```
------------------------------------------------------------------------
24-Jan-2024 16:35:59 - Running job #1
------------------------------------------------------------------------
24-Jan-2024 16:36:00 - Running 'Import'
24-Jan-2024 16:36:00 - Failed  'Import'
Brace indexing is not supported for variables of this type.
In file "/Users/dominik/Documents/PublicData/PsPM/src/pspm_cfg/pspm_update_struct.m" (???), function "pspm_update_struct" at line 13.
In file "/Users/dominik/Documents/PublicData/PsPM/src/pspm_cfg/pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 87.

The following modules did not run:
Failed: Import
If the problem can be fixed without modifying the job, the computation can be resumed by running
   cfg_util('cont',1)
from the MATLAB command line.
```

**Comment by teddychao** [comment]
> The first step (import) of the GLM tutorial yields the following error:
> 
> ```
> ------------------------------------------------------------------------
> 24-Jan-2024 16:35:59 - Running job #1
> ------------------------------------------------------------------------
> 24-Jan-2024 16:36:00 - Running 'Import'
> 24-Jan-2024 16:36:00 - Failed  'Import'
> Brace indexing is not supported for variables of this type.
> In file "/Users/dominik/Documents/PublicData/PsPM/src/pspm_cfg/pspm_update_struct.m" (???), function "pspm_update_struct" at line 13.
> In file "/Users/dominik/Documents/PublicData/PsPM/src/pspm_cfg/pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 87.
> 
> The following modules did not run:
> Failed: Import
> If the problem can be fixed without modifying the job, the computation can be resumed by running
>    cfg_util('cont',1)
> from the MATLAB command line.
> ```

I apologise for this stupid error. I have fixed this bug systemically now. Please allow me to do some more tests...

**Comment by teddychao** [comment]
Tested the new version and found it working now
Not to overwrite:
image
Overwrite:
image

**Review by dominikbach — APPROVED** [review]

**Pull request merged**
