### PR TITLE
Sort missing epochs in pspm_dcm

### LINKED ISSUE #280: Empty epochs in pspm_dcm
### Summary
Missing epochs are not sorted in pspm_dcm. Due to #224, missing epochs may not appear in order. This leads to empty epochs which cannot be processed.

### (Optional) Possible Cause and Solutions
sort missing epochs in pspm_dcm and merge if overlapping.

### PR DESCRIPTION
**Pull request by dominikbach**
Fixes #280 

Changes proposed in this pull request:
- sort missing epochs in pspm_dcm
- fix additional bug in the detection and processing of "short" missing epochs - at the moment these are not ignored if missing epochs are defined per missing epochs file, and they are incorrectly used when defined as NaN values

### CODE REVIEW

**Comment by dominikbach** [comment]
Manually checked that missing epochs are indeed used in the inversion.

**Comment by dominikbach** [comment]
Fixed a bug detected by Juliana.

**Comment by teddychao** [comment]
@dominikbach Could I know if you mind me to have a look at *pspm_split_sessions*? I think currently the loaded missing epochs during running *pspm_dcm* are empty.. I guess some modifications would be required in *pspm_split_sessions*. I am happy to have a look if you don't mind.

**Comment by dominikbach** [comment]
@teddychao Can you explain the problem? Are you referring to Juliana's test data? I explained in my emails.

**Review by teddychao — APPROVED** [review]

**Pull request merged**
