### PR TITLE
Fix Issue 239

### PR DESCRIPTION
**Pull request by teddychao**
Fixes # .

Changes proposed in this pull request:
- Update the return value of model channel.

### CODE REVIEW

**Comment by dominikbach** [comment]
Ok

**Review by dominikbach — APPROVED** [review]

**Review by SerenXia — APPROVED** [review]
works :)

Thank you.

But I have another issue with the model inversion. I will open a new issue to report it.

**Review by SerenXia — COMMENTED** [review]
it should not use pupil channel!
it should be 'sps_l' or 'sps_r' or 'sps'

**Comment by teddychao** [comment]
Hi @SerenXia  Thank you for the comments. Just could I confirm with you something? 

1. When I was reviewing the code, I noticed that the options of *sps Channel* include *Best eye*, *Last left eye*, and *Last right eye*.
2. In the script *pspm_cfg_glm_sps*, which is written by Tmoser, channel *Last left eye* is linked to variables like *pupil_l*. The right eye is linking to *pupil_r* similarly.
3. In the script *pspm_cfg_glm_sps*, no specification was provided for *sps_l*, *sps_r*, and *sps*.
4. In the script *pspm_glm*, there is some specification for *model.channel* at line 50, which is
> DEFAULT: last channel of the specified modality (for PSR this is 'pupil')

Based on these evidence, I assume *pupil_l* or *pupil_r* should be selected when users specify *Last left eye*, and *Last right eye*. If *sps_l* and *sps_r* are preferred, could you please let me know which situation would be applied to? I am confused about your situation as I feel it could be another situation which was not included in the situations described above.

Thanks

**Review by SerenXia — COMMENTED** [review]
> Hi @SerenXia Thank you for the comments. Just could I confirm with you something?
> 
> 1. When I was reviewing the code, I noticed that the options of _sps Channel_ include _Best eye_, _Last left eye_, and _Last right eye_.
> 2. In the script _pspm_cfg_glm_sps_, which is written by Tmoser, channel _Last left eye_ is linked to variables like _pupil_l_. The right eye is linking to _pupil_r_ similarly.
> 3. In the script _pspm_cfg_glm_sps_, no specification was provided for _sps_l_, _sps_r_, and _sps_.
> 4. In the script _pspm_glm_, there is some specification for _model.channel_ at line 50, which is
> 
> > DEFAULT: last channel of the specified modality (for PSR this is 'pupil')
> 
> Based on these evidences, I assume _pupil_l_ or _pupil_r_ should be selected when users specify _Last left eye_, and _Last right eye_. If _sps_l_ and _sps_r_ are preferred, could you please let me know which situation would be applied to? I am confused about your situation as I feel it could be another situation which was not included in the situations described above.
> 
> Thanks

Hi @teddychao ,

So pupil channels contained pupil size data, sps channels contained scanning data. The sps channels were generated from gaze data - gaze data contains the coordinates of fixation points on the screen. Sps means, scanpath speed, i.e. the speed of how participants moved their eyes and fixation points on the screen. 

according to point 2, in the script pspm_cfg_glm_sps, last left eye should be linked to sps_l, because, this means, "I want to analyse the scanning speed of the left eye", similarly last right eye should be linked to sps_r.

point 3, if there is no specification for sps, please add them :) (I suppose you could simply change most of "pupil" to "sps" in this specific script :)

point 4,  DEFAULT: last channel of the specified modality (for PSR this is 'pupil'), so for SPS this is "sps"

To be noted, all the changes should be only applied to functions and scripts for "sps". If it is for PS or PSR (pupil size response), then Last_left_eye of course should be linked to 'pupil_l' because this means "I want to analyse the pupil size of the left eye". Shortly, pupil, gaze, and sps are different data of eyes.

As you may find in the example data I sent to you,

channel 1: markers
channel 2: pupil_l (pupil size of left eye
channel 3: gaze_x_l (x coordinates of fixation point of the left eye)
channel 4: gaze_y_l (y coordinates of left eye
channel 5-7: similar to 2-4 but of right eye
some other channels added due to preprocessing of pupil data
last two channels: sps_l and sps_r, so scanpath speed of left/right eye

**Comment by teddychao** [comment]
@SerenXia Thank you for the very clear explanation. I have understood the comments and will modify it. Just could I confirm with you that the scripts *pspm_cfg_glm_sps* should handle only the modality *sps*, and *psr* is another modality which should not be handled here?

**Comment by SerenXia** [comment]
> @SerenXia Thank you for the very clear explanation. I have understood the comments and will modify the code. Just could I confirm with you that the scripts _pspm_cfg_glm_sps_ should handle only the modality _sps_, and _psr_ is another modality which should not be handled here?

@teddychao exactly!
so pspm_cfg_glm_sps has the name for sps, it should only deal with sps data. psr was addressed in psps_cfg_glm_ps_fc.

I quickly checked the scripts: pspm_cfg_glm_sps and pspm_cfg_run_glm_sps, so simply change pupil to sps in most of codes should fix the bug. 

BTW, the explanation comments in the two scripts are not adapted to sps (the scripts are adapted from heart period scripts, so probably Tobias forgot to change some of the comments in the scripts :) please update the explanation comments in the two scripts as well. I can help if you have any question on that.

**Pull request merged**
